# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ fabric_1.16 ]
  pull_request:
    branches: [ fabric_1.16 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: dev-build
        path: build/libs/inventoryprofilesnext-fabric-1.17-?.?.?.jar
        retention-days: 3
    - name: Finish
      run: echo="${{ github.event.commits[0].message }}"
